[package]
name = "semantic_version"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"
description = "A library for working with semantic versioning in gpui and Zed"

[lints]
workspace = true

[lib]
path = "src/semantic_version.rs"

[dependencies]
hotpath = { version = "0.6", optional = true }
channels-console = { version = "0.3", optional = true, features=['tokio', 'futures'] }
anyhow.workspace = true
serde.workspace = true

[features]
hotpath = ["dep:hotpath", "hotpath/hotpath"]
hotpath-alloc-bytes-total = ["hotpath/hotpath-alloc-bytes-total"]
hotpath-alloc-count-total = ["hotpath/hotpath-alloc-count-total"]
hotpath-off = ["hotpath/hotpath-off"]
channels-console = ["dep:channels-console"]
