[package]
name = "zlog_settings"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/zlog_settings.rs"

[features]
hotpath = ["dep:hotpath", "hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

hotpath-off = ["hotpath/hotpath-off"]

default = []

[dependencies]
hotpath = { version = "0.7", optional = true }

gpui.workspace = true
collections.workspace = true
settings.workspace = true
zlog.workspace = true
