[package]
name = "http_client"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"
description = "A HTTP client library for Zed and GPUI"

[lints]
workspace = true

[features]
hotpath = ["dep:hotpath", "hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

hotpath-off = ["hotpath/hotpath-off"]

test-support = []

[lib]
path = "src/http_client.rs"
doctest = true

[dependencies]
hotpath = { version = "0.7", optional = true }

anyhow.workspace = true
async-compression.workspace = true
async-fs.workspace = true
async-tar.workspace = true
bytes.workspace = true
derive_more.workspace = true
futures.workspace = true
http-body.workspace = true
http.workspace = true
log.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
url.workspace = true
util.workspace = true
