[package]
name = "rich_text"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/rich_text.rs"
doctest = false

[features]
hotpath = ["dep:hotpath", "hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

hotpath-off = ["hotpath/hotpath-off"]
channels-console = ["dep:channels-console"]
test-support = [
    "gpui/test-support",
    "util/test-support",
]

[dependencies]
hotpath = { version = "0.7", optional = true }
channels-console = { version = "0.3", optional = true, features=['tokio', 'futures'] }
futures.workspace = true
gpui.workspace = true
language.workspace = true
linkify.workspace = true
pulldown-cmark.workspace = true
theme.workspace = true
ui.workspace = true
util.workspace = true
