[package]
name = "worktree_benchmarks"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
hotpath = { version = "0.7", optional = true }

fs.workspace = true
gpui = { workspace = true, features = ["windows-manifest"] }
settings.workspace = true
worktree.workspace = true


[features]
hotpath = ["dep:hotpath", "hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

hotpath-off = ["hotpath/hotpath-off"]

[lints]
workspace = true
