[package]
name = "html_to_markdown"
version = "0.1.0"
description = "Convert HTML to Markdown"
repository = "https://github.com/zed-industries/zed"
documentation = "https://docs.rs/html_to_markdown"
keywords = ["html", "markdown", "html-to-markdown"]
edition.workspace = true
publish = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/html_to_markdown.rs"

[dependencies]
hotpath = { version = "0.6", optional = true }
channels-console = { version = "0.3", optional = true, features=['tokio', 'futures'] }
anyhow.workspace = true
html5ever.workspace = true
markup5ever_rcdom.workspace = true
regex.workspace = true


[features]
hotpath = ["dep:hotpath", "hotpath/hotpath"]
hotpath-alloc-bytes-total = ["hotpath/hotpath-alloc-bytes-total"]
hotpath-alloc-count-total = ["hotpath/hotpath-alloc-count-total"]
hotpath-off = ["hotpath/hotpath-off"]
channels-console = ["dep:channels-console"]
[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
